server:
  port: 8081

spring:
  jpa:
    # 指定是否在spring容器启动时创建表，默认false
    generate-ddl: true
    # 在控制台是否显示SQL语句，默认false
    show-sql: true
    # 指定应用重启后不重新更新表内容
    hibernate:
      ddl-auto: none

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8
    username: root
    password: legendary

  # 指定当前微服务名称
  application:
    name: abcmsc-provider-depart

# 配置日志
logging:
  pattern:
    console: level-%level %msg%n
  level:
    root: info
    org.hibernate: info
    # 在show-sql为true时显示SQL中的动态参数值
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    # 在show-sql为true时显示查询结果
    org.hibernate.hql.internal.ast.exec.BasicExecutor: trace
    com.abc: debug

# eureka简单配置方式
eureka:
  client:
    service-url:
      # 指定当前client所要连接的eureka server
      defaultZone: http://localhost:8000/eureka
  instance:
    instance-id: abcmsc-provider-8081


info:
  app.auth: Reythor
  app.name: abcmsc
  company.name: www.kaikeba.com

# eureka复杂配置方式
#eureka:
#  client:
#    # 指定区域名称
#    region: xxx,yyy,zzz
#    # 指定区域中所包含的地带zone
#    availability-zones:
#      xxx: kkb1, kkb2
#    # 指定各个地带zone中所包含的eureka server地址
#    service-url:
#      kkb1: http://localhost:8000/eureka
#      kkb2: http://localhost:8000/eureka
#    # 指定要连接的注册中心所在区域
#    fetch-remote-regions-registry: xxx