server:
  port: 8000

eureka:
  client:
    register-with-eureka: false  # 指定当前主机是否需要向Eureka Server注册自己(eureka不需要注册自己)
    fetch-registry: false # 指定当前主机是否需要从Eureka Server下载服务注册表
    service-url:
      # 当前eureka server 对外暴露的服务地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
      defaultZone: http://localhost:8000/eureka
  server:
    # eureka自我保护机制的阈值，默认0.85
    renewal-percent-threshold: 0.75
    # 关闭eureka自我保护机制，默认为true
    enable-self-preservation: false

